// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Calendari {
	/**
	 * 
	 */
	public Usuari idUsuariCal;
	/**
	 * 
	 */
	public int idEntrenamentCal;
	/**
	 * 
	 */
	public int idPartit;

	/**
	 * 
	 */
	public void crearCalendari() {
	}

	/**
	 * 
	 */
	public void modificarCalendari() {
	}
};
