// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Convocatoria {
	/**
	 * 
	 */
	public int idUsuariResposta;
	/**
	 * 
	 */
	public String Resposta;
	/**
	 * 
	 */
	public Usuari usuari;
	/**
	 * 
	 */
	public Formulari formulari;

	/**
	 * 
	 */
	public void afegirResposta() {
	}
};
