// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Entrenament {
	/**
	 * 
	 */
	public int idEntrenament;
	/**
	 * 
	 */
	public Date data;
	/**
	 * 
	 */
	public String descripcio;

	/**
	 * 
	 */
	public void afegirEntrenament() {
	}

	/**
	 * 
	 */
	public void cancelarEntrenament() {
	}

	/**
	 * 
	 */
	public void modificarEntrenament() {
	}
};
