// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Equips {
	/**
	 * 
	 */
	public int idEquip;
	/**
	 * 
	 */
	public Especialitat idEspecialitat;
	/**
	 * 
	 */
	public String nomEquip;
	/**
	 * 
	 */
	public String tag;
	/**
	 * 
	 */
	public EquipJugador equipjugador;

	/**
	 * 
	 */
	public void afegirEquips() {
	}

	/**
	 * 
	 */
	public void actualitzarEquip() {
	}
};
