// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class EquipJugador {
	/**
	 * 
	 */
	public Usuari idUsuari;
	/**
	 * 
	 */
	public Equips idEquip;

	/**
	 * 
	 */
	public void afegirJugadorEquip() {
	}

	/**
	 * 
	 */
	public void borrarJugadorEquip() {
	}
};
