// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Especialitat {
	/**
	 * 
	 */
	public int idEspecialitat;
	/**
	 * 
	 */
	public String descripcio;
	/**
	 * 
	 */
	public UsersRols usersrols;

	/**
	 * 
	 * @param descripcio 
	 */
	public void altaEspecialitatDB(String descripcio) {
	}
};
