// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Formulari {
	/**
	 * 
	 */
	public Usuari idCreador;
	/**
	 * 
	 */
	public int idFormulari;
	/**
	 * 
	 */
	public String pregunta;
	/**
	 * 
	 */
	public String data;
	/**
	 * 
	 */
	public String hora;
	/**
	 * 
	 */
	public Equips idEquip;
	/**
	 * 
	 */
	public Usuari usuari;

	/**
	 * 
	 */
	public void afegirFormulari() {
	}

	/**
	 * 
	 */
	public void borrarFormulari() {
	}
};
