// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Helper {
	/**
	 * 
	 */
	public void comprobarIDUser() {
	}

	/**
	 * 
	 */
	public void comprobarIDFormulari() {
	}

	/**
	 * 
	 */
	public void comprobarIDEntrenament() {
	}

	/**
	 * 
	 */
	public void comprobarIDEquips() {
	}

	/**
	 * 
	 */
	public void comprobarRol() {
	}

	/**
	 * 
	 */
	public void comprobarIDEspecialitat() {
	}

	/**
	 * 
	 */
	public void comprobarIDRespForm() {
	}

	/**
	 * 
	 */
	public void comprobarIDPartit() {
	}
};
