// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
interface Main {
	/**
	 * 
	 */
	public void altes();

	/**
	 * 
	 */
	public void modificar();

	/**
	 * 
	 */
	public void forms();

	/**
	 * 
	 */
	public void auxiliar();

	/**
	 * 
	 */
	public void calendari();
};
