// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Partits {
	/**
	 * 
	 */
	public Equips idEquip;
	/**
	 * 
	 */
	public Especialitat idEspecialitat;
	/**
	 * 
	 */
	public String resultat;
	/**
	 * 
	 */
	public String equipRival;

	/**
	 * 
	 */
	public void afegirPartit() {
	}

	/**
	 * 
	 */
	public void actualizar() {
	}
};
