// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Rol {
	/**
	 * 
	 */
	public int idRol;
	/**
	 * 
	 */
	public String tipus;
	/**
	 * 
	 */
	public String descripcio;
	/**
	 * 
	 */
	public UsersRols usersrols;

	/**
	 * 
	 */
	public void afegirRol() {
	}
};
