// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class UsersRols {
	/**
	 * 
	 */
	public Usuari idUsuari;
	/**
	 * 
	 */
	public Rol idRol;
	/**
	 * 
	 */
	public Especialitat idEspecialitat;
	/**
	 * 
	 */
	public String dataComençament;
	/**
	 * 
	 */
	public String dataFinal;

	/**
	 * 
	 */
	public void afegirUsuariRol() {
	}

	/**
	 * 
	 */
	public void finalitzarUsuariRol() {
	}
};
