// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package project;

/************************************************************/
/**
 * 
 */
public class Usuari {
	/**
	 * 
	 */
	public String idUsuari;
	/**
	 * 
	 */
	public String nom;
	/**
	 * 
	 */
	public String cognom;
	/**
	 * 
	 */
	public String dataAniversari;
	/**
	 * 
	 */
	public int telefon;
	/**
	 * 
	 */
	public String password;

	/**
	 * 
	 */
	public void borrarUsuari() {
	}

	/**
	 * 
	 */
	public void modificarDades() {
	}

	/**
	 * 
	 */
	public void altaUserRolDB() {
	}
};
